version: "3.9"

services:
  app:
    container_name: app
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - IP_ADDRESS=0.0.0.0
      - PORT=8011
    ports:
      - "8011:8011"
    volumes:
      - ./volumes/app-data:/app/project

networks:
  default:
    external: true
    name: hairdresser
    driver: bridge

