name: Upload binary to server

on:
  push:
    branches: "main"

jobs:
  linter_check:
    permissions:
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clippy check
        run: rustup component add clippy
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
  build:
    runs-on: ubuntu-latest
    needs: linter_check
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
  upload_artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build release
        uses: actions/checkout@v3
      - run: cargo build --release
      
      - name: Upload binary file
        uses: actions/upload-artifact@v3
        with:
          path: ./target/release/backend-lacquer
          name: backend-laqcuer
          
  make_docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:          
      - uses: actions/checkout@v3
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: khadievedem/devops
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: Dockerfile
  
  run_on_the_server:
    runs-on: ubuntu-latest
    needs: make_docker_image
    steps:
      - name: Executing run.sh on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd  ~/Development/course_work/backend-bin/distfiles/
            docker pull khadievedem/devops:latest
            chmod +x ./run.sh
            ./run.sh
          
