name: Upload binary to server

on:
  push:
    branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
      
  upload_artifacts:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Build release
        uses: actions/checkout@v3
      - run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          path: ./target/release/backend-lacquer
          name: backend-laqcuer
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./docker-compose.yml
          name: docker-compose.yml
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./Dockerfile
          name: Dockerfile
          
      - uses: actions/upload-artifact@v3
        with:
          path: ./run.sh
          name: run.sh

      - uses: actions/download-artifact@v3
        with:
          name: backend-laqcuer
          path: distfiles
       
      - uses: actions/download-artifact@v3
        with:
          name: docker-compose.yml
          path: distfiles
          
      - uses: actions/download-artifact@v3
        with:
          name: Dockerfile
          path: distfiles
          
      - uses: actions/download-artifact@v3
        with:
          name: run.sh
          path: distfiles
  
  upload_to_the_server:
    runs-on: ubuntu-latest
    needs: upload_artifacts
    steps:
      - name: Upload to the server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          source: distfiles/*
          target: ~/Development/course_work/backend-bin/
          key: ${{ secrets.SSH_KEY }}
          timeout: 100s
  
  run_on_the_server:
    runs-on: ubuntu-latest
    needs: upload_artifacts
    steps:
      - name: Executing run.sh on the server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd  ~/Development/course_work/backend-bin/distfiles/
            chmod +x ./run.sh
            ./run.sh
          
